server:
  port: 0

spring:
  application:
    name: catalog-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AndreaJBV/230816-central-config-EB-C1/tree/main
        enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
