server:
  port: ${PORT:${SERVER_PORT:0}}

idRandom: ${random.value}

spring:
  application:
    name: catalog-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AndreaJBV/230816-central-config-EB-C1/tree/main
        enabled: false
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27018
  rabbitmq:
    username: LocalRabbitMQMessagingQueue
    password: af3c4d5d01d790acc
    host: localhost
    port: 5672

queue:
  movie:
    name: MovieQueue
  serie:
    name: SerieQueue

management:
  healt:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      students:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 4
        failureRateThreshold: 50
        waitOurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true

retry:
  instances:
    students:
      waitDuration: 1000
      maxAttempts: 2
      retryExceptions:
        - feign.FeignException$InternalServerError


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
